### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by yinglili666** [lllllllllllll-llll/NSSADNN_IQA#2]
Thank you for your contribution. I trained with your code to get the model.pth file. How should I test it

**Comment by lllllllllllll-llll** [comment]
Hi! I will release the code for cross database test: training on LIVE and test on TID2013, CSIQ or other IQA databases. The code for calculate the SROCC and PLCC values of cross database test is writen by matlab, and i will release soon. I think you mean the code for cross database test, right?

**Comment by yinglili666** [comment]
> Hi! I will release the code for cross database test: training on LIVE and test on TID2013, CSIQ or other IQA databases. The code for calculate the SROCC and PLCC values of cross database test is writen by matlab, and i will release soon. I think you mean the code for cross database test, right?
yes, I want to ,ake a cross test. thank you very much

**Comment by yinglili666** [comment]
> Hi! I will release the code for cross database test: training on LIVE and test on TID2013, CSIQ or other IQA databases. The code for calculate the SROCC and PLCC values of cross database test is writen by matlab, and i will release soon. I think you mean the code for cross database test, right?

I have another question is that your mos.txt sames different from the original dmos.mat, could you tell me how to make the mos.txt? thank you
